---
kind: pipeline
name: test-bazel
steps:
- name: query
  image: l.gcr.io/google/bazel:0.28.0
  commands:
  - env | sort
  - bazel query //...
  volumes:
  - name: cache
    path: /root/.cache

- name: test
  image: l.gcr.io/google/bazel:0.28.0
  commands:
  - ./hack/build/test.sh
  volumes:
  - name: cache
    path: /root/.cache

- name: build and push docker image
  image: l.gcr.io/google/bazel:0.28.0
  environment:
    DOCKER_AUTH:
      from_secret: docker-config-json
  commands:
  - ./hack/build/release-image.sh
  volumes:
  - name: cache
    path: /root/.cache
  when:
    branch:
    - master
    event:
    - tag
    - push

- name: build binaries
  image: l.gcr.io/google/bazel:0.28.0
  environment:
    DOCKER_AUTH:
      from_secret: docker-config-json
  commands:
  - ./hack/build/build-binaries.sh
  volumes:
  - name: cache
    path: /root/.cache
  when:
    branch:
    - master
    event:
    - tag
    - push

- name: publish release
  image: busybox
#  settings:
#    api_key: xxxxxxxx
#    files: dist/*
  commands:
  - ls -lh bazel-bin/
  volumes:
  - name: cache
    path: /root/.cache
  when:
    branch:
    - master
    event:
    - tag
    - push

volumes:
- name: cache
  temp: {}
---
kind: signature
hmac: 1b423c8a79625f17c9340ab4c4136fc7e72472e5bc90b07c3768adb811b9eea4

...
