---
kind: pipeline
name: default

steps:
- name: testbazel
  image: l.gcr.io/google/bazel:0.28.0
  commands:
  - env
  - bazel query //...
---
kind: signature
hmac: ba7a5bb3bf94844d981b9b2b63013492061b868e8fd9ec1384490379668e09da

...
