---
kind: pipeline
name: default

steps:
- name: query
  image: l.gcr.io/google/bazel:0.28.0
  commands:
  - env | sort
  - bazel query //...
  - ls -la
- name: test
  image: l.gcr.io/google/bazel:0.28.0
  commands:
  - ./hack/test.sh
  - ls -la
---
kind: signature
hmac: 6a60e352aadd0188199393aff4fa8552af8375d736f274409bcabfb9b24ea2ba

...
