---
kind: pipeline
name: default

steps:
- name: testbazel
  image: gcr.io/google/bazel:0.28.1
  commands:
  - env
  - bazel query //...
---
kind: signature
hmac: 216de69a168d12ff551c2ca17b048fddde7d89574f416941a1ce89104d5308fa

...
