---
kind: pipeline
name: test-bazel

steps:
- name: query
  image: l.gcr.io/google/bazel:0.28.0
  commands:
  - env | sort
  - bazel query //...
  - cat /root/.docker/config.json
  volumes:
  - name: cache
    path: /root/.cache
- name: test
  image: l.gcr.io/google/bazel:0.28.0
  commands:
  - ./hack/test.sh
  volumes:
  - name: cache
    path: /root/.cache
- name: build
  image: l.gcr.io/google/bazel:0.28.0
  commands:
  - ./hack/build.sh
  volumes:
  - name: cache
    path: /root/.cache

volumes:
- name: cache
  temp: {}
image_pull_secrets:
- test-secret
---
kind: signature
hmac: c830c66648a722e339cc05f747b8a2b0200efdd9cf6d4c3f8fafb1de608d2a36

...
