---
kind: pipeline
name: test-bazel
steps:
- name: query
  image: l.gcr.io/google/bazel:0.28.0
  commands:
  - env | sort
  - bazel query //...
  volumes:
  - name: cache
    path: /root/.cache
- name: test
  image: l.gcr.io/google/bazel:0.28.0
  commands:
  - ./hack/test.sh
  volumes:
  - name: cache
    path: /root/.cache
- name: build
  image: l.gcr.io/google/bazel:0.28.0
  commands:
  - ./hack/build.sh
  volumes:
  - name: cache
    path: /root/.cache
- name: build and push docker image
  image: l.gcr.io/google/bazel:0.28.0
  environment:
    DOCKER_AUTH:
      from_secret: docker-config-json
  commands:
  - ./hack/drone-release-image.sh
  volumes:
  - name: cache
    path: /root/.cache
  when:
    branch:
    - master

volumes:
- name: cache
  temp: {}
---
kind: signature
hmac: 669e5e810f339abf409a40bf2742c83c9496aa579b394b1e7300d3c42e50eb8b

...
