---
kind: pipeline
name: test-bazel
steps:
- name: query
  image: l.gcr.io/google/bazel:0.28.0
  commands:
  - env | sort
  - bazel query //...
  volumes:
  - name: cache
    path: /root/.cache
- name: test
  image: l.gcr.io/google/bazel:0.28.0
  commands:
  - ./hack/test.sh
  volumes:
  - name: cache
    path: /root/.cache
- name: build
  image: l.gcr.io/google/bazel:0.28.0
  commands:
  - ./hack/build.sh
  volumes:
  - name: cache
    path: /root/.cache
- name: build and push docker image
  image: l.gcr.io/google/bazel:0.28.0
  environment:
    DOCKER_AUTH:
      from_secret: docker-config-json
  commands:
  - ./hack/release-image.sh
  volumes:
  - name: cache
    path: /root/.cache
  when:
    branch:
    - master

volumes:
- name: cache
  temp: {}
---
kind: signature
hmac: e7e5f41cf1b826bdaa26fc3b180717fcafd817265bda8cbc182126c1c4a3034f

...
