---
kind: pipeline
name: test-bazel

steps:
- name: query
  image: l.gcr.io/google/bazel:0.28.0
  commands:
  - env | sort
  - bazel query //...
  - cat .docker/config.json
  volumes:
  - name: cache
    path: /root/.cache
- name: test
  image: l.gcr.io/google/bazel:0.28.0
  commands:
  - ./hack/test.sh
  volumes:
  - name: cache
    path: /root/.cache
- name: build
  image: l.gcr.io/google/bazel:0.28.0
  commands:
  - ./hack/build.sh
  volumes:
  - name: cache
    path: /root/.cache

volumes:
- name: cache
  temp: {}
---
kind: signature
hmac: 5d30d2eed7e32bfb96482ca7c17b92333890f72034558f8fd51c9f8eef9e5138

...
