---
kind: pipeline
name: default

steps:
- name: testenv
  image: busybox
  commands:
  - env
  - echo ok
---
kind: signature
hmac: 7205dce80c99e6b7adf80e064540ef29d661d1d1ddae1231f762df29466c48a7

...
