---
kind: pipeline
name: default

steps:
- name: query
  image: l.gcr.io/google/bazel:0.28.0
  commands:
  - env | sort
  - bazel query //...
- name: test
  image: l.gcr.io/google/bazel:0.28.0
  commands:
  - ./hack/test.sh
---
kind: signature
hmac: 1e20123a7401f846f3c3f8d7b8ad073e221df5eb2220ffb8fe66f1dd88c36829

...
