name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  Action:
    runs-on: ubuntu-20.04
    container:
      image: l.gcr.io/google/bazel:3.5.0
      volumes:
        - bazel_cache:/root/.cache
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: Query
        run: |
          env | sort
          bazel query //...
      - name: Test
        run: ./hack/build/test.sh
       # with:
       #   who-to-greet: 'Mona the Octocat'
       # id: hello
