name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  query:
    runs-on: ubuntu-20.04
    container: l.gcr.io/google/bazel:3.5.0
    steps:
      # This step uses GitHub's hello-world-javascript-action: https://github.com/actions/hello-world-javascript-action
      - name: Hello world
        run: |
          env | sort
          bazel query//...
       # with:
       #   who-to-greet: 'Mona the Octocat'
       # id: hello
